import React, { createContext, useContext, useState } from 'react';

const translations = {
  uz: {
    code: 'uz', name: "O'zbek", flag: '🇺🇿',
    home: 'Bosh sahifa', quizzes: 'Quizlar', leaderboard: 'Reyting',
    createQuiz: 'Quiz yaratish', login: 'Kirish', register: "Ro'yxat",
    profile: 'Profilim', admin: 'Admin Panel', logout: 'Chiqish',
    freeBadge: 'Bepul, doim!',
    heroTitle1: 'Bilimingizni sinang,', heroTitle2: 'Dunyoni zabt eting!',
    heroDesc: "Quiz yarating, o'ynang va global reyting jadvalida o'z o'rningizni egallang.",
    viewQuizzes: "Quizlarni ko'rish", createQuizBtn: 'Quiz yaratish', registerNow: "Ro'yxatdan o'tish",
    whyTitle: 'Nima uchun QuizApp?', whySubtitle: 'Hamma narsa bir joyda',
    feature1Title: 'Quiz yaratish', feature1Desc: "O'z savollaringizni qo'shing, 4 ta variant va to'g'ri javobni belgilang.",
    feature2Title: 'Taymer', feature2Desc: "Har bir savol uchun vaqt chegarasi — tezlik va bilimni bir vaqtda sinang.",
    feature3Title: 'Reyting', feature3Desc: "Global reyting jadvalida boshqalar bilan raqobatlashing.",
    feature4Title: 'Natijalar', feature4Desc: "Har bir savolning to'g'ri javobini va tushuntirishini ko'ring.",
    ctaTitle: 'Hoziroq boshlang!', ctaDesc: "Minglab quiz o'yinchilari bilan qo'shiling. Bepul!",
    ctaBtn: "Bepul ro'yxatdan o'tish",
    quizzesTitle: 'Quizlar', quizzesSubtitle: "Istalgan mavzuda quiz toping va o'ynang",
    addQuiz: '+ Quiz yaratish', searchPlaceholder: 'Qidirish...',
    allCategories: 'Hammasi', allDifficulties: 'Hammasi',
    noQuizFound: 'Quiz topilmadi', noQuizFoundDesc: "Filtrlarni o'zgartiring yoki yangi quiz yarating",
    play: "O'ynash", prev: '← Oldingi', next: 'Keyingi →', questions: 'savol', times: 'marta',
    globalRating: 'Global Reyting', bestPlayers: "Eng yaxshi o'yinchilar",
    noPlayers: "Hali hech kim o'ynamagan. Birinchi bo'ling!",
    totalScore: 'umumiy ball', gamesPlayed: "ta o'yin",
    loginTitle: 'Tizimga kirish', loginSubtitle: 'Hisobingizga kiring',
    emailLabel: 'Email', passwordLabel: 'Parol',
    loginBtn: 'Kirish', loggingIn: 'Kirilmoqda...',
    noAccount: "Hisob yo'qmi?", registerLink: "Ro'yxatdan o'tish",
    emailRequired: 'Email kiritilishi shart', emailInvalid: "Email noto'g'ri", passwordRequired: 'Parol kiritilishi shart',
    registerTitle: 'Hisob yaratish', registerSubtitle: "QuizApp'ga qo'shiling — bepul!",
    usernameLabel: 'Username', confirmPasswordLabel: 'Parolni tasdiqlash',
    createAccountBtn: 'Hisob yaratish', creating: 'Yaratilmoqda...',
    hasAccount: 'Hisob bormi?', loginLink: 'Kirish',
    usernameMin: 'Username kamida 3 ta harf', emailWrong: "Email noto'g'ri",
    passwordMin: 'Parol kamida 6 ta belgi', passwordMismatch: 'Parollar mos emas',
    myProfile: 'Mening profilim', editProfile: 'Tahrirlash', save: 'Saqlash',
    saving: 'Saqlanmoqda...', cancel: 'Bekor', security: 'Xavfsizlik',
    changePassword: "Parolni o'zgartirish", cancelChange: 'Bekor qilish',
    currentPassword: 'Joriy parol', newPassword: 'Yangi parol', confirmPassword: 'Tasdiqlash', updateBtn: 'Yangilash',
    created: 'Yaratilgan', played: "O'ynagan", totalScoreLabel: 'Jami ball',
    myQuizzes: 'Mening quizlarim', noQuizYet: 'Hali quiz yaratmagansiz', createFirst: 'Birinchi quizni yaratish',
    createQuizTitle: 'Quiz yaratish', createQuizSubtitle: "Ma'lumotlarni to'ldiring va savollar qo'shing",
    quizInfo: "Quiz ma'lumotlari", titleLabel: 'Sarlavha *', titlePlaceholder: 'masalan: Dunyo geografiyasi',
    descLabel: 'Tavsif', descPlaceholder: 'Quiz haqida qisqacha...',
    categoryLabel: 'Kategoriya', difficultyLabel: 'Qiyinchilik',
    timeLimitLabel: 'Vaqt (soniya/savol)', addQuestion: "Savol qo'shish",
    questionLabel: 'Savol matni *', questionPlaceholder: 'Savolingizni yozing...',
    optionsLabel: "Javob variantlari (to'g'ri javobni belgilash uchun doirani bosing)",
    correctMark: "to'g'ri javob sifatida belgilangan",
    explanationLabel: 'Tushuntirish (ixtiyoriy)', explanationPlaceholder: "Nima uchun bu javob to'g'ri?",
    publish: '🚀 Nashr qilish', cancelBtn: 'Bekor qilish',
    deleteQuestion: "O'chirish", questionNum: '-savol',
    titleRequired: 'Sarlavha kiritilishi shart',
    questionEmpty: "-savol matni bo'sh", optionsRequired: "-savolda barcha variantlar to'ldirilishi shart",
    minOneQuestion: "Kamida 1 ta savol bo'lishi kerak",
    editQuizTitle: 'Quizni tahrirlash', editQuizSubtitle: "O'zgartirishlarni saqlang", saveBtn: '💾 Saqlash',
    startBtn: 'Boshlash', backBtn: 'Orqaga',
    quizFinished: 'Quiz yakunlandi!', yourScore: 'Natijangiz:',
    correct: "To'g'ri", wrong: "Noto'g'ri", total: 'Jami',
    reviewAnswers: "Javoblarni ko'rish", topResults: '🏆 Top natijalar',
    replay: "🔄 Qayta o'ynash", quizList: "Quizlar ro'yxati", globalLeaderboard: '🏆 Global reyting',
    timeUp: '⏰ Vaqt tugadi', nextQuestion: 'Keyingi savol →', finish: '🏁 Yakunlash',
    yourAnswer: 'Sizning javobingiz:', correctAnswer: "To'g'ri javob:", questionOf: 'savol',
    adminTitle: 'Admin Panel', adminSubtitle: 'Foydalanuvchilar va quizlarni boshqarish',
    tabOverview: 'Umumiy', tabUsers: 'Foydalanuvchilar', tabQuizzes: 'Quizlar',
    users: 'Foydalanuvchilar', quizzesCount: 'Quizlar', games: "O'yinlar",
    topScores: '🏆 Eng yuqori natijalar',
    colUser: 'Foydalanuvchi', colEmail: 'Email', colPassword: 'Shifrlangan parol',
    colRole: 'Rol', colDate: 'Sana', colActions: 'Amallar',
    colTitle: 'Sarlavha', colAuthor: 'Muallif', colQuestions: 'Savollar', colPlays: "O'yinlar", colScore: 'Ball',
    usersCount: 'ta foydalanuvchi', quizzesCountLabel: 'ta quiz',
    confirmDeleteUser: "Bu foydalanuvchini o'chirmoqchimisiz?", confirmDeleteQuiz: "Bu quizni o'chirmoqchimisiz?",
    catAll: 'Hammasi', catGeneral: 'Umumiy', catScience: 'Fan', catHistory: 'Tarix',
    catTech: 'Texnologiya', catSport: 'Sport', catMusic: 'Musiqa', catCinema: 'Kino',
    diffEasy: 'Oson', diffMedium: "O'rta", diffHard: 'Qiyin',
  },
  ru: {
    code: 'ru', name: 'Русский', flag: '🇷🇺',
    home: 'Главная', quizzes: 'Викторины', leaderboard: 'Рейтинг',
    createQuiz: 'Создать викторину', login: 'Войти', register: 'Регистрация',
    profile: 'Мой профиль', admin: 'Панель админа', logout: 'Выйти',
    freeBadge: 'Бесплатно, навсегда!',
    heroTitle1: 'Проверьте свои знания,', heroTitle2: 'Покорите мир!',
    heroDesc: 'Создавайте викторины, играйте и занимайте место в глобальном рейтинге.',
    viewQuizzes: 'Смотреть викторины', createQuizBtn: 'Создать викторину', registerNow: 'Зарегистрироваться',
    whyTitle: 'Почему QuizApp?', whySubtitle: 'Всё в одном месте',
    feature1Title: 'Создание викторин', feature1Desc: 'Добавляйте свои вопросы, 4 варианта и отмечайте правильный ответ.',
    feature2Title: 'Таймер', feature2Desc: 'Ограничение времени на каждый вопрос — проверяйте скорость и знания.',
    feature3Title: 'Рейтинг', feature3Desc: 'Соревнуйтесь с другими в глобальном рейтинге.',
    feature4Title: 'Результаты', feature4Desc: 'Смотрите правильные ответы и объяснения к каждому вопросу.',
    ctaTitle: 'Начните прямо сейчас!', ctaDesc: 'Присоединяйтесь к тысячам игроков. Бесплатно!',
    ctaBtn: 'Зарегистрироваться бесплатно',
    quizzesTitle: 'Викторины', quizzesSubtitle: 'Найдите и сыграйте в викторину на любую тему',
    addQuiz: '+ Создать викторину', searchPlaceholder: 'Поиск...',
    allCategories: 'Все', allDifficulties: 'Все',
    noQuizFound: 'Викторины не найдены', noQuizFoundDesc: 'Измените фильтры или создайте новую викторину',
    play: 'Играть', prev: '← Назад', next: 'Вперёд →', questions: 'вопросов', times: 'раз',
    globalRating: 'Глобальный рейтинг', bestPlayers: 'Лучшие игроки',
    noPlayers: 'Никто ещё не играл. Будьте первым!',
    totalScore: 'общий балл', gamesPlayed: 'игр',
    loginTitle: 'Вход в систему', loginSubtitle: 'Войдите в свой аккаунт',
    emailLabel: 'Email', passwordLabel: 'Пароль',
    loginBtn: 'Войти', loggingIn: 'Вход...',
    noAccount: 'Нет аккаунта?', registerLink: 'Зарегистрироваться',
    emailRequired: 'Email обязателен', emailInvalid: 'Неверный email', passwordRequired: 'Пароль обязателен',
    registerTitle: 'Создать аккаунт', registerSubtitle: 'Присоединяйтесь к QuizApp — бесплатно!',
    usernameLabel: 'Имя пользователя', confirmPasswordLabel: 'Подтвердите пароль',
    createAccountBtn: 'Создать аккаунт', creating: 'Создание...',
    hasAccount: 'Уже есть аккаунт?', loginLink: 'Войти',
    usernameMin: 'Имя пользователя минимум 3 символа', emailWrong: 'Неверный email',
    passwordMin: 'Пароль минимум 6 символов', passwordMismatch: 'Пароли не совпадают',
    myProfile: 'Мой профиль', editProfile: 'Редактировать', save: 'Сохранить',
    saving: 'Сохранение...', cancel: 'Отмена', security: 'Безопасность',
    changePassword: 'Изменить пароль', cancelChange: 'Отмена',
    currentPassword: 'Текущий пароль', newPassword: 'Новый пароль', confirmPassword: 'Подтверждение', updateBtn: 'Обновить',
    created: 'Создано', played: 'Сыграно', totalScoreLabel: 'Общий балл',
    myQuizzes: 'Мои викторины', noQuizYet: 'Вы ещё не создали викторины', createFirst: 'Создать первую викторину',
    createQuizTitle: 'Создать викторину', createQuizSubtitle: 'Заполните данные и добавьте вопросы',
    quizInfo: 'Данные викторины', titleLabel: 'Название *', titlePlaceholder: 'например: География мира',
    descLabel: 'Описание', descPlaceholder: 'Краткое описание викторины...',
    categoryLabel: 'Категория', difficultyLabel: 'Сложность',
    timeLimitLabel: 'Время (сек/вопрос)', addQuestion: 'Добавить вопрос',
    questionLabel: 'Текст вопроса *', questionPlaceholder: 'Напишите ваш вопрос...',
    optionsLabel: 'Варианты ответа (нажмите круг, чтобы отметить правильный)',
    correctMark: 'отмечен как правильный',
    explanationLabel: 'Объяснение (необязательно)', explanationPlaceholder: 'Почему этот ответ правильный?',
    publish: '🚀 Опубликовать', cancelBtn: 'Отмена',
    deleteQuestion: 'Удалить', questionNum: '-й вопрос',
    titleRequired: 'Название обязательно',
    questionEmpty: '-й вопрос пуст', optionsRequired: '-й вопрос: все варианты должны быть заполнены',
    minOneQuestion: 'Минимум 1 вопрос',
    editQuizTitle: 'Редактировать викторину', editQuizSubtitle: 'Сохраните изменения', saveBtn: '💾 Сохранить',
    startBtn: 'Начать', backBtn: 'Назад',
    quizFinished: 'Викторина завершена!', yourScore: 'Ваш результат:',
    correct: 'Правильно', wrong: 'Неправильно', total: 'Всего',
    reviewAnswers: 'Просмотр ответов', topResults: '🏆 Топ результаты',
    replay: '🔄 Играть снова', quizList: 'Список викторин', globalLeaderboard: '🏆 Глобальный рейтинг',
    timeUp: '⏰ Время вышло', nextQuestion: 'Следующий вопрос →', finish: '🏁 Завершить',
    yourAnswer: 'Ваш ответ:', correctAnswer: 'Правильный ответ:', questionOf: 'вопрос',
    adminTitle: 'Панель админа', adminSubtitle: 'Управление пользователями и викторинами',
    tabOverview: 'Обзор', tabUsers: 'Пользователи', tabQuizzes: 'Викторины',
    users: 'Пользователи', quizzesCount: 'Викторины', games: 'Игры',
    topScores: '🏆 Лучшие результаты',
    colUser: 'Пользователь', colEmail: 'Email', colPassword: 'Хэш пароля',
    colRole: 'Роль', colDate: 'Дата', colActions: 'Действия',
    colTitle: 'Название', colAuthor: 'Автор', colQuestions: 'Вопросы', colPlays: 'Игры', colScore: 'Балл',
    usersCount: 'пользователей', quizzesCountLabel: 'викторин',
    confirmDeleteUser: 'Удалить этого пользователя?', confirmDeleteQuiz: 'Удалить эту викторину?',
    catAll: 'Все', catGeneral: 'Общее', catScience: 'Наука', catHistory: 'История',
    catTech: 'Технологии', catSport: 'Спорт', catMusic: 'Музыка', catCinema: 'Кино',
    diffEasy: 'Лёгкий', diffMedium: 'Средний', diffHard: 'Сложный',
  },
  en: {
    code: 'en', name: 'English', flag: '🇬🇧',
    home: 'Home', quizzes: 'Quizzes', leaderboard: 'Leaderboard',
    createQuiz: 'Create Quiz', login: 'Login', register: 'Register',
    profile: 'My Profile', admin: 'Admin Panel', logout: 'Logout',
    freeBadge: 'Free, forever!',
    heroTitle1: 'Test your knowledge,', heroTitle2: 'Conquer the world!',
    heroDesc: 'Create quizzes, play and claim your spot on the global leaderboard.',
    viewQuizzes: 'Browse Quizzes', createQuizBtn: 'Create Quiz', registerNow: 'Get Started',
    whyTitle: 'Why QuizApp?', whySubtitle: 'Everything in one place',
    feature1Title: 'Create Quizzes', feature1Desc: 'Add your own questions, 4 choices, and mark the correct answer.',
    feature2Title: 'Timer', feature2Desc: 'Time limit per question — test your speed and knowledge simultaneously.',
    feature3Title: 'Leaderboard', feature3Desc: 'Compete with others on the global leaderboard.',
    feature4Title: 'Results', feature4Desc: 'See the correct answer and explanation for every question.',
    ctaTitle: 'Start now!', ctaDesc: 'Join thousands of quiz players. Free!',
    ctaBtn: 'Register for free',
    quizzesTitle: 'Quizzes', quizzesSubtitle: 'Find and play a quiz on any topic',
    addQuiz: '+ Create Quiz', searchPlaceholder: 'Search...',
    allCategories: 'All', allDifficulties: 'All',
    noQuizFound: 'No quizzes found', noQuizFoundDesc: 'Change filters or create a new quiz',
    play: 'Play', prev: '← Previous', next: 'Next →', questions: 'questions', times: 'plays',
    globalRating: 'Global Leaderboard', bestPlayers: 'Top Players',
    noPlayers: 'Nobody has played yet. Be the first!',
    totalScore: 'total score', gamesPlayed: 'games',
    loginTitle: 'Sign In', loginSubtitle: 'Log in to your account',
    emailLabel: 'Email', passwordLabel: 'Password',
    loginBtn: 'Login', loggingIn: 'Logging in...',
    noAccount: "Don't have an account?", registerLink: 'Register',
    emailRequired: 'Email is required', emailInvalid: 'Invalid email', passwordRequired: 'Password is required',
    registerTitle: 'Create Account', registerSubtitle: 'Join QuizApp — for free!',
    usernameLabel: 'Username', confirmPasswordLabel: 'Confirm Password',
    createAccountBtn: 'Create Account', creating: 'Creating...',
    hasAccount: 'Already have an account?', loginLink: 'Login',
    usernameMin: 'Username must be at least 3 characters', emailWrong: 'Invalid email',
    passwordMin: 'Password must be at least 6 characters', passwordMismatch: "Passwords don't match",
    myProfile: 'My Profile', editProfile: 'Edit', save: 'Save',
    saving: 'Saving...', cancel: 'Cancel', security: 'Security',
    changePassword: 'Change Password', cancelChange: 'Cancel',
    currentPassword: 'Current Password', newPassword: 'New Password', confirmPassword: 'Confirm', updateBtn: 'Update',
    created: 'Created', played: 'Played', totalScoreLabel: 'Total Score',
    myQuizzes: 'My Quizzes', noQuizYet: "You haven't created any quizzes yet", createFirst: 'Create your first quiz',
    createQuizTitle: 'Create Quiz', createQuizSubtitle: 'Fill in the details and add questions',
    quizInfo: 'Quiz Details', titleLabel: 'Title *', titlePlaceholder: 'e.g. World Geography',
    descLabel: 'Description', descPlaceholder: 'Brief description of the quiz...',
    categoryLabel: 'Category', difficultyLabel: 'Difficulty',
    timeLimitLabel: 'Time (seconds/question)', addQuestion: 'Add Question',
    questionLabel: 'Question Text *', questionPlaceholder: 'Write your question...',
    optionsLabel: 'Answer options (click the circle to mark the correct answer)',
    correctMark: 'marked as correct',
    explanationLabel: 'Explanation (optional)', explanationPlaceholder: 'Why is this answer correct?',
    publish: '🚀 Publish', cancelBtn: 'Cancel',
    deleteQuestion: 'Delete', questionNum: ' question',
    titleRequired: 'Title is required',
    questionEmpty: ' question text is empty', optionsRequired: ' question: all options must be filled',
    minOneQuestion: 'At least 1 question is required',
    editQuizTitle: 'Edit Quiz', editQuizSubtitle: 'Save your changes', saveBtn: '💾 Save',
    startBtn: 'Start', backBtn: 'Back',
    quizFinished: 'Quiz Finished!', yourScore: 'Your Score:',
    correct: 'Correct', wrong: 'Wrong', total: 'Total',
    reviewAnswers: 'Review Answers', topResults: '🏆 Top Results',
    replay: '🔄 Play Again', quizList: 'Quiz List', globalLeaderboard: '🏆 Global Leaderboard',
    timeUp: '⏰ Time Up', nextQuestion: 'Next Question →', finish: '🏁 Finish',
    yourAnswer: 'Your answer:', correctAnswer: 'Correct answer:', questionOf: 'question',
    adminTitle: 'Admin Panel', adminSubtitle: 'Manage users and quizzes',
    tabOverview: 'Overview', tabUsers: 'Users', tabQuizzes: 'Quizzes',
    users: 'Users', quizzesCount: 'Quizzes', games: 'Games',
    topScores: '🏆 Top Scores',
    colUser: 'User', colEmail: 'Email', colPassword: 'Password Hash',
    colRole: 'Role', colDate: 'Date', colActions: 'Actions',
    colTitle: 'Title', colAuthor: 'Author', colQuestions: 'Questions', colPlays: 'Plays', colScore: 'Score',
    usersCount: 'users', quizzesCountLabel: 'quizzes',
    confirmDeleteUser: 'Delete this user?', confirmDeleteQuiz: 'Delete this quiz?',
    catAll: 'All', catGeneral: 'General', catScience: 'Science', catHistory: 'History',
    catTech: 'Technology', catSport: 'Sports', catMusic: 'Music', catCinema: 'Cinema',
    diffEasy: 'Easy', diffMedium: 'Medium', diffHard: 'Hard',
  },
  tg: {
    code: 'tg', name: 'Тоҷикӣ', flag: '🇹🇯',
    home: 'Саҳифаи асосӣ', quizzes: 'Викторинаҳо', leaderboard: 'Рейтинг',
    createQuiz: 'Викторина сохтан', login: 'Даромадан', register: 'Бақайдгирӣ',
    profile: 'Профили ман', admin: 'Панели админ', logout: 'Баромадан',
    freeBadge: 'Ройгон, ҳамеша!',
    heroTitle1: 'Дониши худро санҷед,', heroTitle2: 'Оламро фатҳ кунед!',
    heroDesc: 'Викторина созед, бозӣ кунед ва дар ҷадвали глобалии рейтинг ҷои худро гиред.',
    viewQuizzes: 'Дидани викторинаҳо', createQuizBtn: 'Викторина сохтан', registerNow: 'Бақайдгирӣ',
    whyTitle: 'Чаро QuizApp?', whySubtitle: 'Ҳама чиз дар як ҷо',
    feature1Title: 'Сохтани викторина', feature1Desc: 'Саволҳои худро илова кунед, 4 вариант ва ҷавоби дурустро нишон диҳед.',
    feature2Title: 'Таймер', feature2Desc: 'Маҳдудияти вақт барои ҳар савол — суръат ва дониш санҷед.',
    feature3Title: 'Рейтинг', feature3Desc: 'Бо дигарон дар ҷадвали глобалии рейтинг рақобат кунед.',
    feature4Title: 'Натиҷаҳо', feature4Desc: 'Ҷавоби дуруст ва тавзеҳоти ҳар саволро бинед.',
    ctaTitle: 'Ҳозир оғоз кунед!', ctaDesc: 'Ба ҳазорон бозингарони викторина ҳамроҳ шавед. Ройгон!',
    ctaBtn: 'Ройгон бақайдгирӣ',
    quizzesTitle: 'Викторинаҳо', quizzesSubtitle: 'Викторинаро дар ҳама мавзӯъ ёбед ва бозӣ кунед',
    addQuiz: '+ Викторина сохтан', searchPlaceholder: 'Ҷустуҷӯ...',
    allCategories: 'Ҳама', allDifficulties: 'Ҳама',
    noQuizFound: 'Викторина ёфт нашуд', noQuizFoundDesc: 'Филтрҳоро иваз кунед ё викторинаи нав созед',
    play: 'Бозӣ кунед', prev: '← Қаблӣ', next: 'Баъдӣ →', questions: 'савол', times: 'маротиба',
    globalRating: 'Рейтинги глобалӣ', bestPlayers: 'Беҳтарин бозингарон',
    noPlayers: 'Ҳоло ҳеҷ кас бозӣ накардааст. Аввалин шавед!',
    totalScore: 'маҷмӯи хол', gamesPlayed: 'бозӣ',
    loginTitle: 'Воридшавӣ', loginSubtitle: 'Ба ҳисоби худ ворид шавед',
    emailLabel: 'Email', passwordLabel: 'Рамз',
    loginBtn: 'Даромадан', loggingIn: 'Воридшавӣ...',
    noAccount: 'Ҳисоб надоред?', registerLink: 'Бақайдгирӣ',
    emailRequired: 'Email ҳатмӣ аст', emailInvalid: 'Email нодуруст', passwordRequired: 'Рамз ҳатмӣ аст',
    registerTitle: 'Ҳисоб созед', registerSubtitle: 'Ба QuizApp ҳамроҳ шавед — ройгон!',
    usernameLabel: 'Номи корбар', confirmPasswordLabel: 'Тасдиқи рамз',
    createAccountBtn: 'Ҳисоб созед', creating: 'Сохтан...',
    hasAccount: 'Ҳисоб доред?', loginLink: 'Даромадан',
    usernameMin: 'Номи корбар ҳадди аққал 3 ҳарф', emailWrong: 'Email нодуруст',
    passwordMin: 'Рамз ҳадди аққал 6 аломат', passwordMismatch: 'Рамзҳо мувофиқ нестанд',
    myProfile: 'Профили ман', editProfile: 'Таҳрир', save: 'Нигоҳ доштан',
    saving: 'Нигоҳ доштан...', cancel: 'Бекор кардан', security: 'Амнияти',
    changePassword: 'Иваз кардани рамз', cancelChange: 'Бекор кардан',
    currentPassword: 'Рамзи ҷорӣ', newPassword: 'Рамзи нав', confirmPassword: 'Тасдиқ', updateBtn: 'Навсозӣ',
    created: 'Сохташуда', played: 'Бозишуда', totalScoreLabel: 'Маҷмӯи хол',
    myQuizzes: 'Викторинаҳои ман', noQuizYet: 'Ҳоло викторина насохтаед', createFirst: 'Аввалин викторинаро созед',
    createQuizTitle: 'Викторина сохтан', createQuizSubtitle: 'Маълумотро пур кунед ва саволҳо илова кунед',
    quizInfo: 'Маълумоти викторина', titleLabel: 'Унвон *', titlePlaceholder: 'масалан: Ҷуғрофии ҷаҳон',
    descLabel: 'Тавсиф', descPlaceholder: 'Тавсифи кӯтоҳи викторина...',
    categoryLabel: 'Категория', difficultyLabel: 'Душворӣ',
    timeLimitLabel: 'Вақт (сония/савол)', addQuestion: 'Илова кардани савол',
    questionLabel: 'Матни савол *', questionPlaceholder: 'Саволи худро нависед...',
    optionsLabel: 'Вариантҳои ҷавоб (доираро пахш кунед то ҷавоби дурустро нишон диҳед)',
    correctMark: 'ҳамчун дуруст нишон дода шудааст',
    explanationLabel: 'Тавзеҳ (ихтиёрӣ)', explanationPlaceholder: 'Чаро ин ҷавоб дуруст аст?',
    publish: '🚀 Нашр кардан', cancelBtn: 'Бекор кардан',
    deleteQuestion: 'Нест кардан', questionNum: '-ум савол',
    titleRequired: 'Унвон ҳатмӣ аст',
    questionEmpty: '-ум савол холӣ аст', optionsRequired: '-ум савол: ҳама вариантҳо пур бошанд',
    minOneQuestion: 'Ҳадди аққал 1 савол',
    editQuizTitle: 'Таҳрири викторина', editQuizSubtitle: 'Тағйиротро нигоҳ доред', saveBtn: '💾 Нигоҳ доштан',
    startBtn: 'Оғоз', backBtn: 'Бозгашт',
    quizFinished: 'Викторина тамом шуд!', yourScore: 'Натиҷаи шумо:',
    correct: 'Дуруст', wrong: 'Нодуруст', total: 'Ҷамъ',
    reviewAnswers: 'Дидани ҷавобҳо', topResults: '🏆 Натиҷаҳои беҳтарин',
    replay: '🔄 Такрор бозӣ кунед', quizList: 'Рӯйхати викторинаҳо', globalLeaderboard: '🏆 Рейтинги глобалӣ',
    timeUp: '⏰ Вақт тамом шуд', nextQuestion: 'Савол баъдӣ →', finish: '🏁 Хотима',
    yourAnswer: 'Ҷавоби шумо:', correctAnswer: 'Ҷавоби дуруст:', questionOf: 'савол',
    adminTitle: 'Панели админ', adminSubtitle: 'Идоракунии корбарон ва викторинаҳо',
    tabOverview: 'Умумӣ', tabUsers: 'Корбарон', tabQuizzes: 'Викторинаҳо',
    users: 'Корбарон', quizzesCount: 'Викторинаҳо', games: 'Бозиҳо',
    topScores: '🏆 Беҳтарин натиҷаҳо',
    colUser: 'Корбар', colEmail: 'Email', colPassword: 'Хэши рамз',
    colRole: 'Нақш', colDate: 'Сана', colActions: 'Амалҳо',
    colTitle: 'Унвон', colAuthor: 'Муаллиф', colQuestions: 'Саволҳо', colPlays: 'Бозиҳо', colScore: 'Хол',
    usersCount: 'корбар', quizzesCountLabel: 'викторина',
    confirmDeleteUser: 'Ин корбарро нест кунед?', confirmDeleteQuiz: 'Ин викторинаро нест кунед?',
    catAll: 'Ҳама', catGeneral: 'Умумӣ', catScience: 'Илм', catHistory: 'Таърих',
    catTech: 'Технология', catSport: 'Варзиш', catMusic: 'Мусиқӣ', catCinema: 'Кино',
    diffEasy: 'Осон', diffMedium: 'Миёна', diffHard: 'Душвор',
  },
  kk: {
    code: 'kk', name: 'Қазақ', flag: '🇰🇿',
    home: 'Басты бет', quizzes: 'Викториналар', leaderboard: 'Рейтинг',
    createQuiz: 'Викторина жасау', login: 'Кіру', register: 'Тіркелу',
    profile: 'Менің профилім', admin: 'Әкімші панелі', logout: 'Шығу',
    freeBadge: 'Тегін, мәңгі!',
    heroTitle1: 'Білімді тексер,', heroTitle2: 'Әлемді бағындыр!',
    heroDesc: 'Викторина жасаңыз, ойнаңыз және жаһандық рейтинг кестесінде орын алыңыз.',
    viewQuizzes: 'Викториналарды көру', createQuizBtn: 'Викторина жасау', registerNow: 'Тіркелу',
    whyTitle: 'Неге QuizApp?', whySubtitle: 'Бәрі бір жерде',
    feature1Title: 'Викторина жасау', feature1Desc: 'Өз сұрақтарыңызды қосыңыз, 4 нұсқа және дұрыс жауапты белгілеңіз.',
    feature2Title: 'Таймер', feature2Desc: 'Әр сұрақ үшін уақыт шегі — жылдамдық пен білімді бір мезгілде тексеріңіз.',
    feature3Title: 'Рейтинг', feature3Desc: 'Жаһандық рейтинг кестесінде басқалармен бәсекелесіңіз.',
    feature4Title: 'Нәтижелер', feature4Desc: 'Әр сұрақтың дұрыс жауабын және түсіндірмесін көріңіз.',
    ctaTitle: 'Қазір бастаңыз!', ctaDesc: 'Мыңдаған ойыншылармен қосылыңыз. Тегін!',
    ctaBtn: 'Тегін тіркелу',
    quizzesTitle: 'Викториналар', quizzesSubtitle: 'Кез келген тақырыпта викторина тауып ойнаңыз',
    addQuiz: '+ Викторина жасау', searchPlaceholder: 'Іздеу...',
    allCategories: 'Барлығы', allDifficulties: 'Барлығы',
    noQuizFound: 'Викторина табылмады', noQuizFoundDesc: 'Сүзгілерді өзгертіңіз немесе жаңа викторина жасаңыз',
    play: 'Ойнау', prev: '← Алдыңғы', next: 'Келесі →', questions: 'сұрақ', times: 'рет',
    globalRating: 'Жаһандық рейтинг', bestPlayers: 'Үздік ойыншылар',
    noPlayers: 'Әлі ешкім ойнаған жоқ. Бірінші болыңыз!',
    totalScore: 'жалпы ұпай', gamesPlayed: 'ойын',
    loginTitle: 'Жүйеге кіру', loginSubtitle: 'Тіркелгіңізге кіріңіз',
    emailLabel: 'Email', passwordLabel: 'Құпиясөз',
    loginBtn: 'Кіру', loggingIn: 'Кіру...',
    noAccount: 'Тіркелгіңіз жоқ па?', registerLink: 'Тіркелу',
    emailRequired: 'Email міндетті', emailInvalid: 'Email қате', passwordRequired: 'Құпиясөз міндетті',
    registerTitle: 'Тіркелгі жасау', registerSubtitle: 'QuizApp-қа қосылыңыз — тегін!',
    usernameLabel: 'Пайдаланушы аты', confirmPasswordLabel: 'Құпиясөзді растау',
    createAccountBtn: 'Тіркелгі жасау', creating: 'Жасалуда...',
    hasAccount: 'Тіркелгіңіз бар ма?', loginLink: 'Кіру',
    usernameMin: 'Пайдаланушы аты кемінде 3 таңба', emailWrong: 'Email қате',
    passwordMin: 'Құпиясөз кемінде 6 таңба', passwordMismatch: 'Құпиясөздер сәйкес емес',
    myProfile: 'Менің профилім', editProfile: 'Өңдеу', save: 'Сақтау',
    saving: 'Сақталуда...', cancel: 'Болдырмау', security: 'Қауіпсіздік',
    changePassword: 'Құпиясөзді өзгерту', cancelChange: 'Болдырмау',
    currentPassword: 'Ағымдағы құпиясөз', newPassword: 'Жаңа құпиясөз', confirmPassword: 'Растау', updateBtn: 'Жаңарту',
    created: 'Жасалған', played: 'Ойналған', totalScoreLabel: 'Жалпы ұпай',
    myQuizzes: 'Менің викториналарым', noQuizYet: 'Сіз әлі викторина жасаған жоқсыз', createFirst: 'Бірінші викторина жасау',
    createQuizTitle: 'Викторина жасау', createQuizSubtitle: 'Деректерді толтырып, сұрақтар қосыңыз',
    quizInfo: 'Викторина деректері', titleLabel: 'Тақырып *', titlePlaceholder: 'мысалы: Әлем географиясы',
    descLabel: 'Сипаттама', descPlaceholder: 'Викторина туралы қысқаша...',
    categoryLabel: 'Санат', difficultyLabel: 'Қиындық',
    timeLimitLabel: 'Уақыт (секунд/сұрақ)', addQuestion: 'Сұрақ қосу',
    questionLabel: 'Сұрақ мәтіні *', questionPlaceholder: 'Сұрағыңызды жазыңыз...',
    optionsLabel: 'Жауап нұсқалары (дұрысты белгілеу үшін шеңберді басыңыз)',
    correctMark: 'дұрыс жауап ретінде белгіленді',
    explanationLabel: 'Түсіндірме (міндетті емес)', explanationPlaceholder: 'Неге бұл жауап дұрыс?',
    publish: '🚀 Жариялау', cancelBtn: 'Болдырмау',
    deleteQuestion: 'Жою', questionNum: '-сұрақ',
    titleRequired: 'Тақырып міндетті',
    questionEmpty: '-сұрақ мәтіні бос', optionsRequired: '-сұрақ: барлық нұсқалар толтырылуы тиіс',
    minOneQuestion: 'Кемінде 1 сұрақ болуы керек',
    editQuizTitle: 'Викторинаны өңдеу', editQuizSubtitle: 'Өзгерістерді сақтаңыз', saveBtn: '💾 Сақтау',
    startBtn: 'Бастау', backBtn: 'Артқа',
    quizFinished: 'Викторина аяқталды!', yourScore: 'Нәтижеңіз:',
    correct: 'Дұрыс', wrong: 'Қате', total: 'Барлығы',
    reviewAnswers: 'Жауаптарды қарау', topResults: '🏆 Үздік нәтижелер',
    replay: '🔄 Қайта ойнау', quizList: 'Викториналар тізімі', globalLeaderboard: '🏆 Жаһандық рейтинг',
    timeUp: '⏰ Уақыт аяқталды', nextQuestion: 'Келесі сұрақ →', finish: '🏁 Аяқтау',
    yourAnswer: 'Сіздің жауабыңыз:', correctAnswer: 'Дұрыс жауап:', questionOf: 'сұрақ',
    adminTitle: 'Әкімші панелі', adminSubtitle: 'Пайдаланушылар мен викториналарды басқару',
    tabOverview: 'Жалпы', tabUsers: 'Пайдаланушылар', tabQuizzes: 'Викториналар',
    users: 'Пайдаланушылар', quizzesCount: 'Викториналар', games: 'Ойындар',
    topScores: '🏆 Үздік нәтижелер',
    colUser: 'Пайдаланушы', colEmail: 'Email', colPassword: 'Құпиясөз хэші',
    colRole: 'Рөл', colDate: 'Күн', colActions: 'Әрекеттер',
    colTitle: 'Тақырып', colAuthor: 'Автор', colQuestions: 'Сұрақтар', colPlays: 'Ойындар', colScore: 'Ұпай',
    usersCount: 'пайдаланушы', quizzesCountLabel: 'викторина',
    confirmDeleteUser: 'Бұл пайдаланушыны жоюды қалайсыз ба?', confirmDeleteQuiz: 'Бұл викторинаны жоюды қалайсыз ба?',
    catAll: 'Барлығы', catGeneral: 'Жалпы', catScience: 'Ғылым', catHistory: 'Тарих',
    catTech: 'Технология', catSport: 'Спорт', catMusic: 'Музыка', catCinema: 'Кино',
    diffEasy: 'Оңай', diffMedium: 'Орташа', diffHard: 'Қиын',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'uz');

  const changeLang = (code) => {
    setLang(code);
    localStorage.setItem('lang', code);
  };

  const t = translations[lang] || translations.uz;

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, languages: translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
